# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on GOOS=linux GOARCH=amd64

go:
  - "1.13"

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step.
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - (cd src/main && make install)

# TODO lint
script:
  - if test -z "${TRAVIS_TAG}" && test -n "${TRAVIS_PULL_REQUEST_SHA}"; then (cd src/main && make test); fi # only run tests on pull requests
  - if test -n "${TRAVIS_TAG}" && test -z "${TRAVIS_PULL_REQUEST_SHA}"; then (cd src/main && VERSION=${TRAVIS_TAG} GOOS=${GOOS} GOARCH=${GOARCH} make build); fi # only run tests on pull requests

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/kommol-${GOOS}-${GOARCH}.tar.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true