# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  - GO111MODULE=on

go:
  - "1.13"

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step.
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - (cd src/main && make install)

# TODO lint
script:
  - (cd src/main && make test)

branches:
  only:
    - master